apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.12.3
apiServerCertSANs:
- k8s-master01
- k8s-node01
- k8s-node02
- k8s-master-lb
- 192.168.2.100
- 192.168.2.101
- 192.168.2.102
- 192.168.2.99
etcd:
  local:
    extraArgs:
      listen-client-urls: "https://127.0.0.1:2379,https://192.168.2.101:2379"
      advertise-client-urls: "https://192.168.2.101:2379"
      listen-peer-urls: "https://192.168.2.101:2380"
      initial-advertise-peer-urls: "https://192.168.2.101:2380"
      initial-cluster: "k8s-master01=https://192.168.2.100:2380,k8s-node01=https://192.168.2.101:2380"
      initial-cluster-state: existing
    serverCertSANs:
      - k8s-node01
      - 192.168.2.101
    peerCertSANs:
      - k8s-node01
      - 192.168.2.101
networking:
  # This CIDR is a calico default. Substitute or remove for your CNI provider.
  podSubnet: "172.168.0.0/16"
